kind: pipeline
type: docker
name: ci/cd
clone:
  disable: true
steps:
  - name: clone
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - mkdir $HOME/.ssh
      - echo -n "$SSH_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git init
      - git remote add origin $DRONE_GIT_SSH_URL
      - git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1
      - git checkout origin/$DRONE_COMMIT_BRANCH -ft
  - name: build docker file and publish
    depends_on:
      - clone
    image: plugins/docker
    pull: if-not-exists
    settings:
      registry: hub.ccw.es
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.oocc.es/home/pnpm
      tags: latest
trigger:
  event:
    exclude:
      - promote
